/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /readAppAccountClass:
 *   get:
 *     tags:
 *       - Administration
 *     description: readAppAccountClass
 *     summary: AppAccountClassRead
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: accountClassId
 *         description: Long 
 *         in: query
 *         type: Long
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    
    var readAppAccountClass = new Promise((resolve, reject) => {
        dao.readAppAccountClass(jsonObj,function(err,rows) {
            if(err) res.status(err.code).end();
            else{
                if(rows[0]===undefined) res.status(404).end();
                else{ 
                    jsonObj = rows[0];
                    resolve(jsonObj);
                }
            }
        });
    });
    
    var appAccountSubClass = new Promise((resolve, reject) => {
        dao.searchAppAccountSubClass(jsonObj,function(err,rows) {
            jsonObj.appAccountSubClass = rows;
            resolve(jsonObj);
        });        
    });
    
    var appRptBalanceSheet = new Promise((resolve, reject) => {
        dao.searchAppRptBalanceSheet(jsonObj,function(err,rows) {
            jsonObj.appRptBalanceSheet = rows;
            resolve(jsonObj);
        });        
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        res.status(200).send(jsonObj);
    }
    
    Promise.all([readAppAccountClass,appAccountSubClass,appRptBalanceSheet]).then(sendResult);
});

module.exports = router;
