/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /readAppProduct:
 *   get:
 *     tags:
 *       - Administration
 *     description: readAppProduct
 *     summary: AppProductRead
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: productId
 *         description: Long 
 *         in: query
 *         type: Long
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    
    var readAppProduct = new Promise((resolve, reject) => {
        dao.readAppProduct(jsonObj,function(err,rows) {
            if(err) res.status(err.code).end();
            else{
                if(rows[0]===undefined) res.status(404).end();
                else{ 
                    jsonObj = rows[0];
                    resolve(jsonObj);
                }
            }
        });
    });
    
    var appInventoryOpenBalance = new Promise((resolve, reject) => {
        dao.searchAppInventoryOpenBalance(jsonObj,function(err,rows) {
            jsonObj.appInventoryOpenBalance = rows;
            resolve(jsonObj);
        });        
    });
    
    var appProductAcctCode = new Promise((resolve, reject) => {
        dao.searchAppProductAcctCode(jsonObj,function(err,rows) {
            jsonObj.appProductAcctCode = rows;
            resolve(jsonObj);
        });        
    });
    
    var appProductImage = new Promise((resolve, reject) => {
        dao.searchAppProductImage(jsonObj,function(err,rows) {
            jsonObj.appProductImage = rows;
            resolve(jsonObj);
        });        
    });
    
    var appProductSellingPrice = new Promise((resolve, reject) => {
        dao.searchAppProductSellingPrice(jsonObj,function(err,rows) {
            jsonObj.appProductSellingPrice = rows;
            resolve(jsonObj);
        });        
    });
    
    var appProductStockInfo = new Promise((resolve, reject) => {
        dao.searchAppProductStockInfo(jsonObj,function(err,rows) {
            jsonObj.appProductStockInfo = rows;
            resolve(jsonObj);
        });        
    });
    
    var appStockCard = new Promise((resolve, reject) => {
        dao.searchAppStockCard(jsonObj,function(err,rows) {
            jsonObj.appStockCard = rows;
            resolve(jsonObj);
        });        
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        res.status(200).send(jsonObj);
    }
    
    Promise.all([readAppProduct,appInventoryOpenBalance,appProductAcctCode,appProductImage,appProductSellingPrice,appProductStockInfo,appStockCard]).then(sendResult);
});

module.exports = router;
