/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /readAppChartOfAccount:
 *   get:
 *     tags:
 *       - Administration
 *     description: readAppChartOfAccount
 *     summary: AppChartOfAccountRead
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: chartOfAccountId
 *         description: Long 
 *         in: query
 *         type: Long
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    
    var readAppChartOfAccount = new Promise((resolve, reject) => {
        dao.readAppChartOfAccount(jsonObj,function(err,rows) {
            if(err) res.status(err.code).end();
            else{
                if(rows[0]===undefined) res.status(404).end();
                else{ 
                    jsonObj = rows[0];
                    resolve(jsonObj);
                }
            }
        });
    });
    
    var appControlAccount = new Promise((resolve, reject) => {
        dao.searchAppControlAccount(jsonObj,function(err,rows) {
            jsonObj.appControlAccount = rows;
            resolve(jsonObj);
        });        
    });
    
    var appGeneralJournalItems = new Promise((resolve, reject) => {
        dao.searchAppGeneralJournalItems(jsonObj,function(err,rows) {
            jsonObj.appGeneralJournalItems = rows;
            resolve(jsonObj);
        });        
    });
    
    var appGeneralLedgerDetail = new Promise((resolve, reject) => {
        dao.searchAppGeneralLedgerDetail(jsonObj,function(err,rows) {
            jsonObj.appGeneralLedgerDetail = rows;
            resolve(jsonObj);
        });        
    });
    
    var appOpeningBalance = new Promise((resolve, reject) => {
        dao.searchAppOpeningBalance(jsonObj,function(err,rows) {
            jsonObj.appOpeningBalance = rows;
            resolve(jsonObj);
        });        
    });
    
    var appRecurringJournalItems = new Promise((resolve, reject) => {
        dao.searchAppRecurringJournalItems(jsonObj,function(err,rows) {
            jsonObj.appRecurringJournalItems = rows;
            resolve(jsonObj);
        });        
    });
    
    var appRptBalanceSheet = new Promise((resolve, reject) => {
        dao.searchAppRptBalanceSheet(jsonObj,function(err,rows) {
            jsonObj.appRptBalanceSheet = rows;
            resolve(jsonObj);
        });        
    });
    
    var appRptCashFlow = new Promise((resolve, reject) => {
        dao.searchAppRptCashFlow(jsonObj,function(err,rows) {
            jsonObj.appRptCashFlow = rows;
            resolve(jsonObj);
        });        
    });
    
    var appSummaryGl = new Promise((resolve, reject) => {
        dao.searchAppSummaryGl(jsonObj,function(err,rows) {
            jsonObj.appSummaryGl = rows;
            resolve(jsonObj);
        });        
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        res.status(200).send(jsonObj);
    }
    
    Promise.all([readAppChartOfAccount,appControlAccount,appGeneralJournalItems,appGeneralLedgerDetail,appOpeningBalance,appRecurringJournalItems,appRptBalanceSheet,appRptCashFlow,appSummaryGl]).then(sendResult);
});

module.exports = router;
