/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchAppProject:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchAppProject
 *     summary: AppProjectSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: projectId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: name
 *         description: String
 *         in: query
 *         type: String
 *       - name: projectManager
 *         description: String
 *         in: query
 *         type: String
 *       - name: details
 *         description: String
 *         in: query
 *         type: String
 *       - name: status
 *         description: String
 *         in: query
 *         type: String
 *       - name: customerId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: isJobOrder
 *         description: String
 *         in: query
 *         type: String
 *       - name: isActive
 *         description: String
 *         in: query
 *         type: String
 *       - name: jobOrderNo
 *         description: String
 *         in: query
 *         type: String
 *       - name: isUsePhase
 *         description: String
 *         in: query
 *         type: String
 *       - name: orderDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: deliveryDate
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: contactPerson
 *         description: String
 *         in: query
 *         type: String
 *       - name: percentageFinish
 *         description: String
 *         in: query
 *         type: String
 *       - name: estimationCostBudget
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: estimationIncomeBudget
 *         description: Double
 *         in: query
 *         type: Double
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchAppProject(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.appProject = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
