/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchAppProductCategory:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchAppProductCategory
 *     summary: AppProductCategorySearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: productCategoryId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: categoryName
 *         description: String
 *         in: query
 *         type: String
 *       - name: location
 *         description: String
 *         in: query
 *         type: String
 *       - name: departmentId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: isInventory
 *         description: String
 *         in: query
 *         type: String
 *       - name: isPurchased
 *         description: String
 *         in: query
 *         type: String
 *       - name: isSold
 *         description: String
 *         in: query
 *         type: String
 *       - name: inventoryMethod
 *         description: String
 *         in: query
 *         type: String
 *       - name: acctCodeCogs
 *         description: String
 *         in: query
 *         type: String
 *       - name: acctCodeSales
 *         description: String
 *         in: query
 *         type: String
 *       - name: acctCodeSalesReturn
 *         description: String
 *         in: query
 *         type: String
 *       - name: acctCodeInventory
 *         description: String
 *         in: query
 *         type: String
 *       - name: acctCodeConsignment
 *         description: String
 *         in: query
 *         type: String
 *       - name: image
 *         description: byte[]
 *         in: query
 *         type: byte[]
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchAppProductCategory(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.appProductCategory = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
