/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchAppCompanyInfoAccPeriod:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchAppCompanyInfoAccPeriod
 *     summary: AppCompanyInfoAccPeriodSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: accountingPeriodId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: month
 *         description: String
 *         in: query
 *         type: String
 *       - name: year
 *         description: String
 *         in: query
 *         type: String
 *       - name: yearEnd
 *         description: String
 *         in: query
 *         type: String
 *       - name: isCreateChartOfAccount
 *         description: String
 *         in: query
 *         type: String
 *       - name: fileName
 *         description: String
 *         in: query
 *         type: String
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchAppCompanyInfoAccPeriod(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.appCompanyInfoAccPeriod = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
