/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchAppSummaryArCustomer:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchAppSummaryArCustomer
 *     summary: AppSummaryArCustomerSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: summaryArCustomerId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: customerId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: date
 *         description: java.util.Date
 *         in: query
 *         type: java.util.Date
 *       - name: beginningBalanceDebit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: beginningBalanceCredit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: debitMutation
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: creditMutation
 *         description: String
 *         in: query
 *         type: String
 *       - name: endingBalanceDebit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: endingBalanceCredit
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: beginningBalance
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: deltaFromBegToEnd
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: endingBalance
 *         description: Double
 *         in: query
 *         type: Double
 *       - name: paid
 *         description: Double
 *         in: query
 *         type: Double
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchAppSummaryArCustomer(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.appSummaryArCustomer = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
