/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var database = require('./dao');
var dao = new database.Dao();
        
/**
 * @swagger
 * /searchAppProduct:
 *   get:
 *     tags:
 *       - Administration
 *     description: searchAppProduct
 *     summary: AppProductSearch
 *     consumes:
 *       - application/json
 *     produces:
 *       - application/json
 *     parameters: 
 *       - name: productId
 *         description: Long
 *         in: query
 *         type: Long
 *       - name: productCode
 *         description: String
 *         in: query
 *         type: String
 *       - name: productDesc
 *         description: String
 *         in: query
 *         type: String
 *       - name: baseUnit
 *         description: String
 *         in: query
 *         type: String
 *       - name: reportUnit
 *         description: String
 *         in: query
 *         type: String
 *       - name: productGroup1st
 *         description: String
 *         in: query
 *         type: String
 *       - name: productGroup2nd
 *         description: String
 *         in: query
 *         type: String
 *       - name: productGroup3rd
 *         description: String
 *         in: query
 *         type: String
 *       - name: productGroup4th
 *         description: String
 *         in: query
 *         type: String
 *       - name: aliasCode
 *         description: String
 *         in: query
 *         type: String
 *       - name: isUseSerialNumber
 *         description: String
 *         in: query
 *         type: String
 *       - name: isUseLot
 *         description: String
 *         in: query
 *         type: String
 *       - name: isConsignment
 *         description: String
 *         in: query
 *         type: String
 *       - name: isNotActive
 *         description: String
 *         in: query
 *         type: String
 *       - name: isSeasonalProduct
 *         description: String
 *         in: query
 *         type: String
 *       - name: productCategoryId
 *         description: Long
 *         in: query
 *         type: Long
 *     responses:
 *       '200':
 *         description: OK
 *       '401':
 *         description: Unauthorized
 *       '403':
 *         description: Forbidden
 *       '404':
 *         description: Not Found 
 *       '500':
 *         description: Internal Server Problem
 */    

router.get('/', function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    dao.searchAppProduct(jsonObj,function(err,rows) {    
        if(err) res.status(err.code).end();
        else {
            jsonObj.appProduct = rows;
            res.status(200).send(jsonObj);
        }
        console.log(jsonObj);        
    });
});

module.exports = router;
