/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppInventoryOpenBalanceDelete',
    Heading:'AppInventoryOpenBalance',
    InventoryOpeningBalanceId:{label :'InventoryOpeningBalanceId'},
    LocationMaster:{label :'LocationMaster'},
    ProductId:{label :'ProductId'},
    BeginningBalance:{label :'BeginningBalance'},
    UnitCost:{label :'UnitCost'},
    IsSerialNumber:{label :'IsSerialNumber'},
    IsLotNumber:{label :'IsLotNumber'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteAppInventoryOpenBalance(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
