/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProjectDelete',
    Heading:'AppProject',
    ProjectId:{label :'ProjectId'},
    Name:{label :'Name'},
    ProjectManager:{label :'ProjectManager'},
    Details:{label :'Details'},
    Status:{label :'Status'},
    CustomerId:{label :'CustomerId'},
    IsJobOrder:{label :'IsJobOrder'},
    IsActive:{label :'IsActive'},
    JobOrderNo:{label :'JobOrderNo'},
    IsUsePhase:{label :'IsUsePhase'},
    OrderDate:{label :'OrderDate'},
    DeliveryDate:{label :'DeliveryDate'},
    ContactPerson:{label :'ContactPerson'},
    PercentageFinish:{label :'PercentageFinish'},
    EstimationCostBudget:{label :'EstimationCostBudget'},
    EstimationIncomeBudget:{label :'EstimationIncomeBudget'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteAppProject(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
