/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductStockInfoDelete',
    Heading:'AppProductStockInfo',
    ProductStockInfoId:{label :'ProductStockInfoId'},
    QtyInStock:{label :'QtyInStock'},
    OrderedToVendor:{label :'OrderedToVendor'},
    OrderedByCustomer:{label :'OrderedByCustomer'},
    MinimumInventory:{label :'MinimumInventory'},
    MinimumOrder:{label :'MinimumOrder'},
    SalesForecast:{label :'SalesForecast'},
    BuyingPrice:{label :'BuyingPrice'},
    ProductId:{label :'ProductId'},
    BuyingPriceTax:{label :'BuyingPriceTax'},
    SellingUnitPriceTax:{label :'SellingUnitPriceTax'},
    UnitCostOrCogs:{label :'UnitCostOrCogs'},
    CogsDepartment:{label :'CogsDepartment'},
    LocationMaster:{label :'LocationMaster'},
    DeliveryTimeIndays:{label :'DeliveryTimeIndays'},
    CurrentSellingPrice:{label :'CurrentSellingPrice'},
    MainVendor:{label :'MainVendor'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteAppProductStockInfo(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
