/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppSummaryArAgingDelete',
    Heading:'AppSummaryArAging',
    ArAgingId:{label :'ArAgingId'},
    CustomerId:{label :'CustomerId'},
    CurrentDate:{label :'CurrentDate'},
    Day030:{label :'Day030'},
    Day3060:{label :'Day3060'},
    Day6090:{label :'Day6090'},
    DayMoreThan90:{label :'DayMoreThan90'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteAppSummaryArAging(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
