/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductCategoryDelete',
    Heading:'AppProductCategory',
    ProductCategoryId:{label :'ProductCategoryId'},
    CategoryName:{label :'CategoryName'},
    Location:{label :'Location'},
    DepartmentId:{label :'DepartmentId'},
    IsInventory:{label :'IsInventory'},
    IsPurchased:{label :'IsPurchased'},
    IsSold:{label :'IsSold'},
    InventoryMethod:{label :'InventoryMethod'},
    AcctCodeCogs:{label :'AcctCodeCogs'},
    AcctCodeSales:{label :'AcctCodeSales'},
    AcctCodeSalesReturn:{label :'AcctCodeSalesReturn'},
    AcctCodeInventory:{label :'AcctCodeInventory'},
    AcctCodeConsignment:{label :'AcctCodeConsignment'},
    Image:{label :'Image'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteAppProductCategory(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
