/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCurrencyNew',
    Heading:'AppCurrency',
    CurrencyId:{label :'CurrencyId'},
    CurrencyCode:{label :'CurrencyCode'},
    CurrencyName:{label :'CurrencyName'},
    CurrencySymbol:{label :'CurrencySymbol'},
    ExchangeRate:{label :'ExchangeRate'},
    ByDate:{label :'ByDate'},
    ControlAccountAr:{label :'ControlAccountAr'},
    ControlAccountAp:{label :'ControlAccountAp'},
    ControlAccountBankPayment:{label :'ControlAccountBankPayment'},
    ControlAccountCashPayment:{label :'ControlAccountCashPayment'},
    IsCurrencyBase:{label :'IsCurrencyBase'},
    IsForeignCurrency:{label :'IsForeignCurrency'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{currencyId:'',
        currencyCode:'',
        currencyName:'',
        currencySymbol:'',
        exchangeRate:'',
        byDate:'',
        controlAccountAr:'',
        controlAccountAp:'',
        controlAccountBankPayment:'',
        controlAccountCashPayment:'',
        isCurrencyBase:'',
        isForeignCurrency:'',
        }
    }
    res.render('AppCurrencyNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppCurrency(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppCurrencyNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
