/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankWcFaNew',
    Heading:'AppBankWcFa',
    BankWcFaId:{label :'BankWcFaId'},
    BankWriteCheckId:{label :'BankWriteCheckId'},
    AccountNo:{label :'AccountNo'},
    DepartmentId:{label :'DepartmentId'},
    Amount:{label :'Amount'},
    JobOrderNo:{label :'JobOrderNo'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{bankWcFaId:'',
        bankWriteCheckId:'',
        accountNo:'',
        departmentId:'',
        amount:'',
        jobOrderNo:'',
        }
    }
    res.render('AppBankWcFaNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppBankWcFa(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppBankWcFaNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
