/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppEmployeeNew',
    Heading:'AppEmployee',
    EmployeeId:{label :'EmployeeId'},
    EmployeeNumber:{label :'EmployeeNumber'},
    Firstname:{label :'Firstname'},
    Middlename:{label :'Middlename'},
    Lastname:{label :'Lastname'},
    Nationality:{label :'Nationality'},
    Dob:{label :'Dob'},
    Gender:{label :'Gender'},
    MaritalStatus:{label :'MaritalStatus'},
    Ethnicity:{label :'Ethnicity'},
    KtpNumber:{label :'KtpNumber'},
    PassportNumber:{label :'PassportNumber'},
    DrivingLicenceNo:{label :'DrivingLicenceNo'},
    AddressLine1:{label :'AddressLine1'},
    AddressLine2:{label :'AddressLine2'},
    CityId:{label :'CityId'},
    CountryId:{label :'CountryId'},
    ProvinceId:{label :'ProvinceId'},
    PostalCode:{label :'PostalCode'},
    HomePhone:{label :'HomePhone'},
    MobilePhone:{label :'MobilePhone'},
    WorkEmail:{label :'WorkEmail'},
    PrivateEmail:{label :'PrivateEmail'},
    JoinedDate:{label :'JoinedDate'},
    ConfirmationDate:{label :'ConfirmationDate'},
    TerminationDate:{label :'TerminationDate'},
    SupervisorName:{label :'SupervisorName'},
    IndirectSupervisorName:{label :'IndirectSupervisorName'},
    FirstLevelApprover:{label :'FirstLevelApprover'},
    SecondLevelApprover:{label :'SecondLevelApprover'},
    ThirdLevelApprover:{label :'ThirdLevelApprover'},
    Notes:{label :'Notes'},
    DepartmentId:{label :'DepartmentId'},
    WorkStationId:{label :'WorkStationId'},
    JobTitleId:{label :'JobTitleId'},
    PayGradeId:{label :'PayGradeId'},
    EmploymentStatusId:{label :'EmploymentStatusId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{employeeId:'',
        employeeNumber:'',
        firstname:'',
        middlename:'',
        lastname:'',
        nationality:'',
        dob:'',
        gender:'',
        maritalStatus:'',
        ethnicity:'',
        ktpNumber:'',
        passportNumber:'',
        drivingLicenceNo:'',
        addressLine1:'',
        addressLine2:'',
        cityId:'',
        countryId:'',
        provinceId:'',
        postalCode:'',
        homePhone:'',
        mobilePhone:'',
        workEmail:'',
        privateEmail:'',
        joinedDate:'',
        confirmationDate:'',
        terminationDate:'',
        supervisorName:'',
        indirectSupervisorName:'',
        firstLevelApprover:'',
        secondLevelApprover:'',
        thirdLevelApprover:'',
        notes:'',
        departmentId:'',
        workStationId:'',
        jobTitleId:'',
        payGradeId:'',
        employmentStatusId:'',
        }
    }
    res.render('AppEmployeeNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppEmployee(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppEmployeeNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
