/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRecurringJournalNew',
    Heading:'AppRecurringJournal',
    RecurringJournalId:{label :'RecurringJournalId'},
    TransactionName:{label :'TransactionName'},
    Frequency:{label :'Frequency'},
    Reference:{label :'Reference'},
    Date:{label :'Date'},
    Note:{label :'Note'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{recurringJournalId:'',
        transactionName:'',
        frequency:'',
        reference:'',
        date:'',
        note:'',
        }
    }
    res.render('AppRecurringJournalNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppRecurringJournal(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppRecurringJournalNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
