/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppArAgingNew',
    Heading:'AppArAging',
    ArAgingId:{label :'ArAgingId'},
    CustomerId:{label :'CustomerId'},
    ReferenceNo:{label :'ReferenceNo'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    ArDueDate:{label :'ArDueDate'},
    CurrentDate:{label :'CurrentDate'},
    Age:{label :'Age'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{arAgingId:'',
        customerId:'',
        referenceNo:'',
        debit:'',
        credit:'',
        arDueDate:'',
        currentDate:'',
        age:'',
        }
    }
    res.render('AppArAgingNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppArAging(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppArAgingNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
