/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppArOpeningBalanceNew',
    Heading:'AppArOpeningBalance',
    ArOpeningBalanceId:{label :'ArOpeningBalanceId'},
    CustomerId:{label :'CustomerId'},
    Date:{label :'Date'},
    InvoiceNo:{label :'InvoiceNo'},
    PurchaseOrderNo:{label :'PurchaseOrderNo'},
    CurrencyId:{label :'CurrencyId'},
    ReceivableValue:{label :'ReceivableValue'},
    TermOfPaymentId:{label :'TermOfPaymentId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{arOpeningBalanceId:'',
        customerId:'',
        date:'',
        invoiceNo:'',
        purchaseOrderNo:'',
        currencyId:'',
        receivableValue:'',
        termOfPaymentId:'',
        }
    }
    res.render('AppArOpeningBalanceNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppArOpeningBalance(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppArOpeningBalanceNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
