/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppStockCardNew',
    Heading:'AppStockCard',
    StockCardId:{label :'StockCardId'},
    ProductId:{label :'ProductId'},
    TransactionDate:{label :'TransactionDate'},
    RefNo:{label :'RefNo'},
    DocType:{label :'DocType'},
    TransactionType:{label :'TransactionType'},
    TransactionQty:{label :'TransactionQty'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{stockCardId:'',
        productId:'',
        transactionDate:'',
        refNo:'',
        docType:'',
        transactionType:'',
        transactionQty:'',
        }
    }
    res.render('AppStockCardNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppStockCard(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppStockCardNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
