/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCurrencyFluctuationNew',
    Heading:'AppCurrencyFluctuation',
    CurrencyFluctuationId:{label :'CurrencyFluctuationId'},
    CurrencyId:{label :'CurrencyId'},
    ByDate:{label :'ByDate'},
    ExchangeRate:{label :'ExchangeRate'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{currencyFluctuationId:'',
        currencyId:'',
        byDate:'',
        exchangeRate:'',
        }
    }
    res.render('AppCurrencyFluctuationNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newAppCurrencyFluctuation(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppCurrencyFluctuationNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
