/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankReconciliationRead',
    Heading:'AppBankReconciliation',
    BankReconciliationId:{label :'BankReconciliationId'},
    AccountNo:{label :'AccountNo'},
    CurrentAccountDate:{label :'CurrentAccountDate'},
    CurrentAccountBalance:{label :'CurrentAccountBalance'},
    AppBankReconciliationDetail:{Heading:'AppBankReconciliationDetail',
        BankReconciliationDetailId:{header:'BankReconciliationDetailId'},
        BankReconciliationId:{header:'BankReconciliationId'},
        Date:{header:'Date'},
        ReferenceNo:{header:'ReferenceNo'},
        Note:{header:'Note'},
        DebitAmount:{header:'DebitAmount'},
        CreditAmount:{header:'CreditAmount'},
        IsSelected:{header:'IsSelected'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppBankReconciliation?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppBankReconciliation = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppBankReconciliation(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppBankReconciliation');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var appBankReconciliationDetail = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAppBankReconciliationDetail(jsonObj,function(err,rows) {
                jsonObj.appBankReconciliationDetail = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppBankReconciliationReadPage',parameter);
    }    
    Promise.all([readAppBankReconciliation,appBankReconciliationDetail]).then(sendResult);
});

module.exports = router;
