/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppSummaryArAgingRead',
    Heading:'AppSummaryArAging',
    ArAgingId:{label :'ArAgingId'},
    CustomerId:{label :'CustomerId'},
    CurrentDate:{label :'CurrentDate'},
    Day030:{label :'Day030'},
    Day3060:{label :'Day3060'},
    Day6090:{label :'Day6090'},
    DayMoreThan90:{label :'DayMoreThan90'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppSummaryArAging?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppSummaryArAging = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppSummaryArAging(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppSummaryArAging');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppSummaryArAgingReadPage',parameter);
    }    
    Promise.all([readAppSummaryArAging]).then(sendResult);
});

module.exports = router;
