/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppStockCardRead',
    Heading:'AppStockCard',
    StockCardId:{label :'StockCardId'},
    ProductId:{label :'ProductId'},
    TransactionDate:{label :'TransactionDate'},
    RefNo:{label :'RefNo'},
    DocType:{label :'DocType'},
    TransactionType:{label :'TransactionType'},
    TransactionQty:{label :'TransactionQty'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppStockCard?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppStockCard = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppStockCard(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppStockCard');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppStockCardReadPage',parameter);
    }    
    Promise.all([readAppStockCard]).then(sendResult);
});

module.exports = router;
