/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppArWriteoffVerificationRead',
    Heading:'AppArWriteoffVerification',
    WriteOffVerificationId:{label :'WriteOffVerificationId'},
    Ref:{label :'Ref'},
    Date:{label :'Date'},
    Amount:{label :'Amount'},
    Note:{label :'Note'},
    AcccountNo:{label :'AcccountNo'},
    AllowanceAccountNo:{label :'AllowanceAccountNo'},
    ReferenceNoTobeWriteoff:{label :'ReferenceNoTobeWriteoff'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppArWriteoffVerification?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppArWriteoffVerification = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppArWriteoffVerification(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppArWriteoffVerification');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppArWriteoffVerificationReadPage',parameter);
    }    
    Promise.all([readAppArWriteoffVerification]).then(sendResult);
});

module.exports = router;
