/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductSellingPriceRead',
    Heading:'AppProductSellingPrice',
    ProductPriceId:{label :'ProductPriceId'},
    ChangedDate:{label :'ChangedDate'},
    ChangedBy:{label :'ChangedBy'},
    NormalPriceEffectiveDate:{label :'NormalPriceEffectiveDate'},
    CalculationMethod:{label :'CalculationMethod'},
    AmountOfCalculationMethod:{label :'AmountOfCalculationMethod'},
    RoundUp:{label :'RoundUp'},
    SmallestUnit:{label :'SmallestUnit'},
    PricingBase:{label :'PricingBase'},
    IsIncludeTaxToSellingPrice:{label :'IsIncludeTaxToSellingPrice'},
    IsSelectedItem:{label :'IsSelectedItem'},
    CurrentSellingPrice:{label :'CurrentSellingPrice'},
    NewSellingPrice:{label :'NewSellingPrice'},
    EffectiveDateOfNewSellingPrice:{label :'EffectiveDateOfNewSellingPrice'},
    ProductId:{label :'ProductId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppProductSellingPrice?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppProductSellingPrice = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppProductSellingPrice(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppProductSellingPrice');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppProductSellingPriceReadPage',parameter);
    }    
    Promise.all([readAppProductSellingPrice]).then(sendResult);
});

module.exports = router;
