/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppTaxRead',
    Heading:'AppTax',
    TaxId:{label :'TaxId'},
    TaxCode:{label :'TaxCode'},
    Tax:{label :'Tax'},
    Percentage:{label :'Percentage'},
    IsCogsDeductible:{label :'IsCogsDeductible'},
    AcctCodePurchaseTax:{label :'AcctCodePurchaseTax'},
    AcctCodeSales:{label :'AcctCodeSales'},
    Details:{label :'Details'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppTax?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppTax = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppTax(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppTax');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppTaxReadPage',parameter);
    }    
    Promise.all([readAppTax]).then(sendResult);
});

module.exports = router;
