/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankCashReceiveRead',
    Heading:'AppBankCashReceive',
    BankCashReceiveId:{label :'BankCashReceiveId'},
    AccountNo:{label :'AccountNo'},
    IsPostDatedCheck:{label :'IsPostDatedCheck'},
    From:{label :'From'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    Amount:{label :'Amount'},
    Memo:{label :'Memo'},
    AppBankCrFa:{Heading:'AppBankCrFa',
        BankCashReceiveDetailId:{header:'BankCashReceiveDetailId'},
        BankCashReceiveId:{header:'BankCashReceiveId'},
        AccountNo:{header:'AccountNo'},
        DepartmentId:{header:'DepartmentId'},
        Amount:{header:'Amount'},
        JobOrderNo:{header:'JobOrderNo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppBankCashReceive?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppBankCashReceive = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppBankCashReceive(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppBankCashReceive');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var appBankCrFa = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.searchAppBankCrFa(jsonObj,function(err,rows) {
                jsonObj.appBankCrFa = rows;
                resolve(jsonObj);
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppBankCashReceiveReadPage',parameter);
    }    
    Promise.all([readAppBankCashReceive,appBankCrFa]).then(sendResult);
});

module.exports = router;
