/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCurrencyRevaluationRead',
    Heading:'AppCurrencyRevaluation',
    CurrencyRevaluationId:{label :'CurrencyRevaluationId'},
    Date:{label :'Date'},
    CurrencyId:{label :'CurrencyId'},
    ExchangeRate:{label :'ExchangeRate'},
    IsActivateAccountFilterType:{label :'IsActivateAccountFilterType'},
    IsActivateAccountCodeFilter:{label :'IsActivateAccountCodeFilter'},
    IsRecalculateAccountEndBalance:{label :'IsRecalculateAccountEndBalance'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppCurrencyRevaluation?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppCurrencyRevaluation = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppCurrencyRevaluation(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppCurrencyRevaluation');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppCurrencyRevaluationReadPage',parameter);
    }    
    Promise.all([readAppCurrencyRevaluation]).then(sendResult);
});

module.exports = router;
