/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCompanyInfoRead',
    Heading:'AppCompanyInfo',
    CompanyInfoId:{label :'CompanyInfoId'},
    CompanyName:{label :'CompanyName'},
    AddressLine1:{label :'AddressLine1'},
    AddressLine2:{label :'AddressLine2'},
    CityId:{label :'CityId'},
    ProvinceId:{label :'ProvinceId'},
    CountryId:{label :'CountryId'},
    PostalCode:{label :'PostalCode'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppCompanyInfo?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppCompanyInfo = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppCompanyInfo(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppCompanyInfo');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppCompanyInfoReadPage',parameter);
    }    
    Promise.all([readAppCompanyInfo]).then(sendResult);
});

module.exports = router;
