/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankReconciliationDetailRead',
    Heading:'AppBankReconciliationDetail',
    BankReconciliationDetailId:{label :'BankReconciliationDetailId'},
    BankReconciliationId:{label :'BankReconciliationId'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    Note:{label :'Note'},
    DebitAmount:{label :'DebitAmount'},
    CreditAmount:{label :'CreditAmount'},
    IsSelected:{label :'IsSelected'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppBankReconciliationDetail?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppBankReconciliationDetail = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppBankReconciliationDetail(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppBankReconciliationDetail');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppBankReconciliationDetailReadPage',parameter);
    }    
    Promise.all([readAppBankReconciliationDetail]).then(sendResult);
});

module.exports = router;
