/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppSummaryArCustomerRead',
    Heading:'AppSummaryArCustomer',
    SummaryArCustomerId:{label :'SummaryArCustomerId'},
    CustomerId:{label :'CustomerId'},
    Date:{label :'Date'},
    BeginningBalanceDebit:{label :'BeginningBalanceDebit'},
    BeginningBalanceCredit:{label :'BeginningBalanceCredit'},
    DebitMutation:{label :'DebitMutation'},
    CreditMutation:{label :'CreditMutation'},
    EndingBalanceDebit:{label :'EndingBalanceDebit'},
    EndingBalanceCredit:{label :'EndingBalanceCredit'},
    BeginningBalance:{label :'BeginningBalance'},
    DeltaFromBegToEnd:{label :'DeltaFromBegToEnd'},
    EndingBalance:{label :'EndingBalance'},
    Paid:{label :'Paid'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readAppSummaryArCustomer?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readAppSummaryArCustomer = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readAppSummaryArCustomer(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchAppSummaryArCustomer');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('AppSummaryArCustomerReadPage',parameter);
    }    
    Promise.all([readAppSummaryArCustomer]).then(sendResult);
});

module.exports = router;
