/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRecurringBankWriteCheckSearch',
    Heading:'AppRecurringBankWriteCheck',
    RecurringBankWriteCheckId:{label :'RecurringBankWriteCheckId'},
    TransactionName:{label :'TransactionName'},
    Frequency:{label :'Frequency'},
    AccountNo:{label :'AccountNo'},
    IsPostDatedCheck:{label :'IsPostDatedCheck'},
    ReceivedBy:{label :'ReceivedBy'},
    Date:{label :'Date'},
    CheckNo:{label :'CheckNo'},
    Amount:{label :'Amount'},
    Memo:{label :'Memo'},
    AppRecurringBankWriteCheck:{Heading:'AppRecurringBankWriteCheck',
        RecurringBankWriteCheckId:{header:'RecurringBankWriteCheckId'},
        TransactionName:{header:'TransactionName'},
        Frequency:{header:'Frequency'},
        AccountNo:{header:'AccountNo'},
        IsPostDatedCheck:{header:'IsPostDatedCheck'},
        ReceivedBy:{header:'ReceivedBy'},
        Date:{header:'Date'},
        CheckNo:{header:'CheckNo'},
        Amount:{header:'Amount'},
        Memo:{header:'Memo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRecurringBankWriteCheck?'+req._parsedUrl.query;
    dao.searchAppRecurringBankWriteCheck(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRecurringBankWriteCheckSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
