/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRestoreInfoSearch',
    Heading:'AppRestoreInfo',
    RestoreInfoId:{label :'RestoreInfoId'},
    ArchiveFileName:{label :'ArchiveFileName'},
    NewLocationFolder:{label :'NewLocationFolder'},
    NewArchiveFileName:{label :'NewArchiveFileName'},
    ServerName:{label :'ServerName'},
    AppRestoreInfo:{Heading:'AppRestoreInfo',
        RestoreInfoId:{header:'RestoreInfoId'},
        ArchiveFileName:{header:'ArchiveFileName'},
        NewLocationFolder:{header:'NewLocationFolder'},
        NewArchiveFileName:{header:'NewArchiveFileName'},
        ServerName:{header:'ServerName'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRestoreInfo?'+req._parsedUrl.query;
    dao.searchAppRestoreInfo(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRestoreInfoSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
