/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCurrencyRevaluationSearch',
    Heading:'AppCurrencyRevaluation',
    CurrencyRevaluationId:{label :'CurrencyRevaluationId'},
    Date:{label :'Date'},
    CurrencyId:{label :'CurrencyId'},
    ExchangeRate:{label :'ExchangeRate'},
    IsActivateAccountFilterType:{label :'IsActivateAccountFilterType'},
    IsActivateAccountCodeFilter:{label :'IsActivateAccountCodeFilter'},
    IsRecalculateAccountEndBalance:{label :'IsRecalculateAccountEndBalance'},
    AppCurrencyRevaluation:{Heading:'AppCurrencyRevaluation',
        CurrencyRevaluationId:{header:'CurrencyRevaluationId'},
        Date:{header:'Date'},
        CurrencyId:{header:'CurrencyId'},
        ExchangeRate:{header:'ExchangeRate'},
        IsActivateAccountFilterType:{header:'IsActivateAccountFilterType'},
        IsActivateAccountCodeFilter:{header:'IsActivateAccountCodeFilter'},
        IsRecalculateAccountEndBalance:{header:'IsRecalculateAccountEndBalance'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppCurrencyRevaluation?'+req._parsedUrl.query;
    dao.searchAppCurrencyRevaluation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppCurrencyRevaluationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
