/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRptBalanceSheetSearch',
    Heading:'AppRptBalanceSheet',
    RptBalanceSheetId:{label :'RptBalanceSheetId'},
    RptBalanceSheetName:{label :'RptBalanceSheetName'},
    DepartmentFrom:{label :'DepartmentFrom'},
    DepartmentTo:{label :'DepartmentTo'},
    CurrencyId:{label :'CurrencyId'},
    AccountClassId:{label :'AccountClassId'},
    AccountSubClassId:{label :'AccountSubClassId'},
    AccountNo:{label :'AccountNo'},
    EndingBalanceDebit:{label :'EndingBalanceDebit'},
    EndingBalanceCredit:{label :'EndingBalanceCredit'},
    ComparativeEndingBalanceDebit:{label :'ComparativeEndingBalanceDebit'},
    ComparativeEndingBalanceCredit:{label :'ComparativeEndingBalanceCredit'},
    DateCreated:{label :'DateCreated'},
    CreatedBy:{label :'CreatedBy'},
    AppRptBalanceSheet:{Heading:'AppRptBalanceSheet',
        RptBalanceSheetId:{header:'RptBalanceSheetId'},
        RptBalanceSheetName:{header:'RptBalanceSheetName'},
        DepartmentFrom:{header:'DepartmentFrom'},
        DepartmentTo:{header:'DepartmentTo'},
        CurrencyId:{header:'CurrencyId'},
        AccountClassId:{header:'AccountClassId'},
        AccountSubClassId:{header:'AccountSubClassId'},
        AccountNo:{header:'AccountNo'},
        EndingBalanceDebit:{header:'EndingBalanceDebit'},
        EndingBalanceCredit:{header:'EndingBalanceCredit'},
        ComparativeEndingBalanceDebit:{header:'ComparativeEndingBalanceDebit'},
        ComparativeEndingBalanceCredit:{header:'ComparativeEndingBalanceCredit'},
        DateCreated:{header:'DateCreated'},
        CreatedBy:{header:'CreatedBy'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRptBalanceSheet?'+req._parsedUrl.query;
    dao.searchAppRptBalanceSheet(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRptBalanceSheetSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
