/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppGeneralLedgerDetailSearch',
    Heading:'AppGeneralLedgerDetail',
    GeneralLedgerDetailId:{label :'GeneralLedgerDetailId'},
    AccountNo:{label :'AccountNo'},
    Date:{label :'Date'},
    Note:{label :'Note'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    Balance:{label :'Balance'},
    ReferenceNo:{label :'ReferenceNo'},
    AppGeneralLedgerDetail:{Heading:'AppGeneralLedgerDetail',
        GeneralLedgerDetailId:{header:'GeneralLedgerDetailId'},
        AccountNo:{header:'AccountNo'},
        Date:{header:'Date'},
        Note:{header:'Note'},
        Debit:{header:'Debit'},
        Credit:{header:'Credit'},
        Balance:{header:'Balance'},
        ReferenceNo:{header:'ReferenceNo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppGeneralLedgerDetail?'+req._parsedUrl.query;
    dao.searchAppGeneralLedgerDetail(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppGeneralLedgerDetailSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
