/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductImageSearch',
    Heading:'AppProductImage',
    ProductImageId:{label :'ProductImageId'},
    Image:{label :'Image'},
    ProductId:{label :'ProductId'},
    AppProductImage:{Heading:'AppProductImage',
        ProductImageId:{header:'ProductImageId'},
        Image:{header:'Image'},
        ProductId:{header:'ProductId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppProductImage?'+req._parsedUrl.query;
    dao.searchAppProductImage(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppProductImageSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
