/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppInventoryOpenBalanceSearch',
    Heading:'AppInventoryOpenBalance',
    InventoryOpeningBalanceId:{label :'InventoryOpeningBalanceId'},
    LocationMaster:{label :'LocationMaster'},
    ProductId:{label :'ProductId'},
    BeginningBalance:{label :'BeginningBalance'},
    UnitCost:{label :'UnitCost'},
    IsSerialNumber:{label :'IsSerialNumber'},
    IsLotNumber:{label :'IsLotNumber'},
    AppInventoryOpenBalance:{Heading:'AppInventoryOpenBalance',
        InventoryOpeningBalanceId:{header:'InventoryOpeningBalanceId'},
        LocationMaster:{header:'LocationMaster'},
        ProductId:{header:'ProductId'},
        BeginningBalance:{header:'BeginningBalance'},
        UnitCost:{header:'UnitCost'},
        IsSerialNumber:{header:'IsSerialNumber'},
        IsLotNumber:{header:'IsLotNumber'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppInventoryOpenBalance?'+req._parsedUrl.query;
    dao.searchAppInventoryOpenBalance(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppInventoryOpenBalanceSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
