/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankDataSearch',
    Heading:'AppBankData',
    BankDataId:{label :'BankDataId'},
    BankAccount:{label :'BankAccount'},
    BankAddress1:{label :'BankAddress1'},
    BankAddress2:{label :'BankAddress2'},
    CityId:{label :'CityId'},
    ZipCode:{label :'ZipCode'},
    AppBankData:{Heading:'AppBankData',
        BankDataId:{header:'BankDataId'},
        BankAccount:{header:'BankAccount'},
        BankAddress1:{header:'BankAddress1'},
        BankAddress2:{header:'BankAddress2'},
        CityId:{header:'CityId'},
        ZipCode:{header:'ZipCode'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppBankData?'+req._parsedUrl.query;
    dao.searchAppBankData(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppBankDataSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
