/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankFundTransferSearch',
    Heading:'AppBankFundTransfer',
    BankFundTransferId:{label :'BankFundTransferId'},
    FromAccountNo:{label :'FromAccountNo'},
    ToAccountNo:{label :'ToAccountNo'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    Amount:{label :'Amount'},
    AppBankFundTransfer:{Heading:'AppBankFundTransfer',
        BankFundTransferId:{header:'BankFundTransferId'},
        FromAccountNo:{header:'FromAccountNo'},
        ToAccountNo:{header:'ToAccountNo'},
        Date:{header:'Date'},
        ReferenceNo:{header:'ReferenceNo'},
        Amount:{header:'Amount'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppBankFundTransfer?'+req._parsedUrl.query;
    dao.searchAppBankFundTransfer(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppBankFundTransferSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
