/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppDepartmentSearch',
    Heading:'AppDepartment',
    DepartmentId:{label :'DepartmentId'},
    DepartmentName:{label :'DepartmentName'},
    DepartmentDesc:{label :'DepartmentDesc'},
    AppDepartment:{Heading:'AppDepartment',
        DepartmentId:{header:'DepartmentId'},
        DepartmentName:{header:'DepartmentName'},
        DepartmentDesc:{header:'DepartmentDesc'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppDepartment?'+req._parsedUrl.query;
    dao.searchAppDepartment(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppDepartmentSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
