/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductCategorySearch',
    Heading:'AppProductCategory',
    ProductCategoryId:{label :'ProductCategoryId'},
    CategoryName:{label :'CategoryName'},
    Location:{label :'Location'},
    DepartmentId:{label :'DepartmentId'},
    IsInventory:{label :'IsInventory'},
    IsPurchased:{label :'IsPurchased'},
    IsSold:{label :'IsSold'},
    InventoryMethod:{label :'InventoryMethod'},
    AcctCodeCogs:{label :'AcctCodeCogs'},
    AcctCodeSales:{label :'AcctCodeSales'},
    AcctCodeSalesReturn:{label :'AcctCodeSalesReturn'},
    AcctCodeInventory:{label :'AcctCodeInventory'},
    AcctCodeConsignment:{label :'AcctCodeConsignment'},
    Image:{label :'Image'},
    AppProductCategory:{Heading:'AppProductCategory',
        ProductCategoryId:{header:'ProductCategoryId'},
        CategoryName:{header:'CategoryName'},
        Location:{header:'Location'},
        DepartmentId:{header:'DepartmentId'},
        IsInventory:{header:'IsInventory'},
        IsPurchased:{header:'IsPurchased'},
        IsSold:{header:'IsSold'},
        InventoryMethod:{header:'InventoryMethod'},
        AcctCodeCogs:{header:'AcctCodeCogs'},
        AcctCodeSales:{header:'AcctCodeSales'},
        AcctCodeSalesReturn:{header:'AcctCodeSalesReturn'},
        AcctCodeInventory:{header:'AcctCodeInventory'},
        AcctCodeConsignment:{header:'AcctCodeConsignment'},
        Image:{header:'Image'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppProductCategory?'+req._parsedUrl.query;
    dao.searchAppProductCategory(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppProductCategorySearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
