/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppMonthEndPeriodSearch',
    Heading:'AppMonthEndPeriod',
    MonthEndPeriodId:{label :'MonthEndPeriodId'},
    Date:{label :'Date'},
    IsCalculateAndCreateDeprJournal:{label :'IsCalculateAndCreateDeprJournal'},
    IsRecalculateAccountBalance:{label :'IsRecalculateAccountBalance'},
    IsRecalculateInventoryAccountBalance:{label :'IsRecalculateInventoryAccountBalance'},
    IsRevaluationForeignCurrency:{label :'IsRevaluationForeignCurrency'},
    AppMonthEndPeriod:{Heading:'AppMonthEndPeriod',
        MonthEndPeriodId:{header:'MonthEndPeriodId'},
        Date:{header:'Date'},
        IsCalculateAndCreateDeprJournal:{header:'IsCalculateAndCreateDeprJournal'},
        IsRecalculateAccountBalance:{header:'IsRecalculateAccountBalance'},
        IsRecalculateInventoryAccountBalance:{header:'IsRecalculateInventoryAccountBalance'},
        IsRevaluationForeignCurrency:{header:'IsRevaluationForeignCurrency'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppMonthEndPeriod?'+req._parsedUrl.query;
    dao.searchAppMonthEndPeriod(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppMonthEndPeriodSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
