/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppYearEndPeriodSearch',
    Heading:'AppYearEndPeriod',
    YearEndPeriodId:{label :'YearEndPeriodId'},
    Date:{label :'Date'},
    Status:{label :'Status'},
    CreatedBy:{label :'CreatedBy'},
    AppYearEndPeriod:{Heading:'AppYearEndPeriod',
        YearEndPeriodId:{header:'YearEndPeriodId'},
        Date:{header:'Date'},
        Status:{header:'Status'},
        CreatedBy:{header:'CreatedBy'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppYearEndPeriod?'+req._parsedUrl.query;
    dao.searchAppYearEndPeriod(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppYearEndPeriodSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
