/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppChartOfAccountSearch',
    Heading:'AppChartOfAccount',
    ChartOfAccountId:{label :'ChartOfAccountId'},
    AccountSubClassId:{label :'AccountSubClassId'},
    AccountNo:{label :'AccountNo'},
    AccountName:{label :'AccountName'},
    IsCashOrBank:{label :'IsCashOrBank'},
    IsNotActive:{label :'IsNotActive'},
    CurrencyId:{label :'CurrencyId'},
    DepartmentId:{label :'DepartmentId'},
    NormalBalance:{label :'NormalBalance'},
    AppChartOfAccount:{Heading:'AppChartOfAccount',
        ChartOfAccountId:{header:'ChartOfAccountId'},
        AccountSubClassId:{header:'AccountSubClassId'},
        AccountNo:{header:'AccountNo'},
        AccountName:{header:'AccountName'},
        IsCashOrBank:{header:'IsCashOrBank'},
        IsNotActive:{header:'IsNotActive'},
        CurrencyId:{header:'CurrencyId'},
        DepartmentId:{header:'DepartmentId'},
        NormalBalance:{header:'NormalBalance'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppChartOfAccount?'+req._parsedUrl.query;
    dao.searchAppChartOfAccount(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppChartOfAccountSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
