/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppTermOfPaymentSearch',
    Heading:'AppTermOfPayment',
    TermOfPaymentId:{label :'TermOfPaymentId'},
    TopCode:{label :'TopCode'},
    TopDesc:{label :'TopDesc'},
    DiscountDaysIndays:{label :'DiscountDaysIndays'},
    DueDateIndays:{label :'DueDateIndays'},
    EarlyDiscountInpercentage:{label :'EarlyDiscountInpercentage'},
    LateChargesInpercentage:{label :'LateChargesInpercentage'},
    AppTermOfPayment:{Heading:'AppTermOfPayment',
        TermOfPaymentId:{header:'TermOfPaymentId'},
        TopCode:{header:'TopCode'},
        TopDesc:{header:'TopDesc'},
        DiscountDaysIndays:{header:'DiscountDaysIndays'},
        DueDateIndays:{header:'DueDateIndays'},
        EarlyDiscountInpercentage:{header:'EarlyDiscountInpercentage'},
        LateChargesInpercentage:{header:'LateChargesInpercentage'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppTermOfPayment?'+req._parsedUrl.query;
    dao.searchAppTermOfPayment(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppTermOfPaymentSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
