/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRefCountrySearch',
    Heading:'AppRefCountry',
    CountryId:{label :'CountryId'},
    Name:{label :'Name'},
    Details:{label :'Details'},
    AppRefCountry:{Heading:'AppRefCountry',
        CountryId:{header:'CountryId'},
        Name:{header:'Name'},
        Details:{header:'Details'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRefCountry?'+req._parsedUrl.query;
    dao.searchAppRefCountry(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRefCountrySearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
