/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppStockCardSearch',
    Heading:'AppStockCard',
    StockCardId:{label :'StockCardId'},
    ProductId:{label :'ProductId'},
    TransactionDate:{label :'TransactionDate'},
    RefNo:{label :'RefNo'},
    DocType:{label :'DocType'},
    TransactionType:{label :'TransactionType'},
    TransactionQty:{label :'TransactionQty'},
    AppStockCard:{Heading:'AppStockCard',
        StockCardId:{header:'StockCardId'},
        ProductId:{header:'ProductId'},
        TransactionDate:{header:'TransactionDate'},
        RefNo:{header:'RefNo'},
        DocType:{header:'DocType'},
        TransactionType:{header:'TransactionType'},
        TransactionQty:{header:'TransactionQty'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppStockCard?'+req._parsedUrl.query;
    dao.searchAppStockCard(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppStockCardSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
