/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCurrencyFluctuationSearch',
    Heading:'AppCurrencyFluctuation',
    CurrencyFluctuationId:{label :'CurrencyFluctuationId'},
    CurrencyId:{label :'CurrencyId'},
    ByDate:{label :'ByDate'},
    ExchangeRate:{label :'ExchangeRate'},
    AppCurrencyFluctuation:{Heading:'AppCurrencyFluctuation',
        CurrencyFluctuationId:{header:'CurrencyFluctuationId'},
        CurrencyId:{header:'CurrencyId'},
        ByDate:{header:'ByDate'},
        ExchangeRate:{header:'ExchangeRate'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppCurrencyFluctuation?'+req._parsedUrl.query;
    dao.searchAppCurrencyFluctuation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppCurrencyFluctuationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
