/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppControlAccountSearch',
    Heading:'AppControlAccount',
    ControlAccountId:{label :'ControlAccountId'},
    ControlAccountName:{label :'ControlAccountName'},
    ControlAccountDesc:{label :'ControlAccountDesc'},
    AccountNo:{label :'AccountNo'},
    AppControlAccount:{Heading:'AppControlAccount',
        ControlAccountId:{header:'ControlAccountId'},
        ControlAccountName:{header:'ControlAccountName'},
        ControlAccountDesc:{header:'ControlAccountDesc'},
        AccountNo:{header:'AccountNo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppControlAccount?'+req._parsedUrl.query;
    dao.searchAppControlAccount(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppControlAccountSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
