/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppApAgingSearch',
    Heading:'AppApAging',
    ApAgingId:{label :'ApAgingId'},
    VendorId:{label :'VendorId'},
    ReferenceNo:{label :'ReferenceNo'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    ApDueDate:{label :'ApDueDate'},
    CurrentDate:{label :'CurrentDate'},
    Age:{label :'Age'},
    AppApAging:{Heading:'AppApAging',
        ApAgingId:{header:'ApAgingId'},
        VendorId:{header:'VendorId'},
        ReferenceNo:{header:'ReferenceNo'},
        Debit:{header:'Debit'},
        Credit:{header:'Credit'},
        ApDueDate:{header:'ApDueDate'},
        CurrentDate:{header:'CurrentDate'},
        Age:{header:'Age'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppApAging?'+req._parsedUrl.query;
    dao.searchAppApAging(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppApAgingSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
