/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBudgetInfoSearch',
    Heading:'AppBudgetInfo',
    BudgetInfoId:{label :'BudgetInfoId'},
    Year:{label :'Year'},
    Month:{label :'Month'},
    Budget:{label :'Budget'},
    Realization:{label :'Realization'},
    AppBudgetInfo:{Heading:'AppBudgetInfo',
        BudgetInfoId:{header:'BudgetInfoId'},
        Year:{header:'Year'},
        Month:{header:'Month'},
        Budget:{header:'Budget'},
        Realization:{header:'Realization'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppBudgetInfo?'+req._parsedUrl.query;
    dao.searchAppBudgetInfo(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppBudgetInfoSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
