/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppAccountSubClassSearch',
    Heading:'AppAccountSubClass',
    AccountSubClassId:{label :'AccountSubClassId'},
    AccountSubClassName:{label :'AccountSubClassName'},
    Note:{label :'Note'},
    AccountClassId:{label :'AccountClassId'},
    AppAccountSubClass:{Heading:'AppAccountSubClass',
        AccountSubClassId:{header:'AccountSubClassId'},
        AccountSubClassName:{header:'AccountSubClassName'},
        Note:{header:'Note'},
        AccountClassId:{header:'AccountClassId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppAccountSubClass?'+req._parsedUrl.query;
    dao.searchAppAccountSubClass(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppAccountSubClassSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
