/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppAdjustmentJournalSearch',
    Heading:'AppAdjustmentJournal',
    AdjustmentJournalId:{label :'AdjustmentJournalId'},
    AccountNo:{label :'AccountNo'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    InOrDebit:{label :'InOrDebit'},
    OutOrCredit:{label :'OutOrCredit'},
    AppAdjustmentJournal:{Heading:'AppAdjustmentJournal',
        AdjustmentJournalId:{header:'AdjustmentJournalId'},
        AccountNo:{header:'AccountNo'},
        Date:{header:'Date'},
        ReferenceNo:{header:'ReferenceNo'},
        InOrDebit:{header:'InOrDebit'},
        OutOrCredit:{header:'OutOrCredit'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppAdjustmentJournal?'+req._parsedUrl.query;
    dao.searchAppAdjustmentJournal(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppAdjustmentJournalSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
