/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductSearch',
    Heading:'AppProduct',
    ProductId:{label :'ProductId'},
    ProductCode:{label :'ProductCode'},
    ProductDesc:{label :'ProductDesc'},
    BaseUnit:{label :'BaseUnit'},
    ReportUnit:{label :'ReportUnit'},
    ProductGroup1st:{label :'ProductGroup1st'},
    ProductGroup2nd:{label :'ProductGroup2nd'},
    ProductGroup3rd:{label :'ProductGroup3rd'},
    ProductGroup4th:{label :'ProductGroup4th'},
    AliasCode:{label :'AliasCode'},
    IsUseSerialNumber:{label :'IsUseSerialNumber'},
    IsUseLot:{label :'IsUseLot'},
    IsConsignment:{label :'IsConsignment'},
    IsNotActive:{label :'IsNotActive'},
    IsSeasonalProduct:{label :'IsSeasonalProduct'},
    ProductCategoryId:{label :'ProductCategoryId'},
    AppProduct:{Heading:'AppProduct',
        ProductId:{header:'ProductId'},
        ProductCode:{header:'ProductCode'},
        ProductDesc:{header:'ProductDesc'},
        BaseUnit:{header:'BaseUnit'},
        ReportUnit:{header:'ReportUnit'},
        ProductGroup1st:{header:'ProductGroup1st'},
        ProductGroup2nd:{header:'ProductGroup2nd'},
        ProductGroup3rd:{header:'ProductGroup3rd'},
        ProductGroup4th:{header:'ProductGroup4th'},
        AliasCode:{header:'AliasCode'},
        IsUseSerialNumber:{header:'IsUseSerialNumber'},
        IsUseLot:{header:'IsUseLot'},
        IsConsignment:{header:'IsConsignment'},
        IsNotActive:{header:'IsNotActive'},
        IsSeasonalProduct:{header:'IsSeasonalProduct'},
        ProductCategoryId:{header:'ProductCategoryId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppProduct?'+req._parsedUrl.query;
    dao.searchAppProduct(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppProductSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
