/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppEmploymentStatusSearch',
    Heading:'AppEmploymentStatus',
    EmploymentStatusId:{label :'EmploymentStatusId'},
    EmploymentStatus:{label :'EmploymentStatus'},
    EmploymentDesc:{label :'EmploymentDesc'},
    AppEmploymentStatus:{Heading:'AppEmploymentStatus',
        EmploymentStatusId:{header:'EmploymentStatusId'},
        EmploymentStatus:{header:'EmploymentStatus'},
        EmploymentDesc:{header:'EmploymentDesc'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppEmploymentStatus?'+req._parsedUrl.query;
    dao.searchAppEmploymentStatus(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppEmploymentStatusSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
