/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRecurringBankCashRcvSearch',
    Heading:'AppRecurringBankCashRcv',
    RecurringBankCashReceiveId:{label :'RecurringBankCashReceiveId'},
    TransactionName:{label :'TransactionName'},
    Frequency:{label :'Frequency'},
    AccountNo:{label :'AccountNo'},
    IsPostDatedCheck:{label :'IsPostDatedCheck'},
    From:{label :'From'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    Amount:{label :'Amount'},
    Memo:{label :'Memo'},
    AppRecurringBankCashRcv:{Heading:'AppRecurringBankCashRcv',
        RecurringBankCashReceiveId:{header:'RecurringBankCashReceiveId'},
        TransactionName:{header:'TransactionName'},
        Frequency:{header:'Frequency'},
        AccountNo:{header:'AccountNo'},
        IsPostDatedCheck:{header:'IsPostDatedCheck'},
        From:{header:'From'},
        Date:{header:'Date'},
        ReferenceNo:{header:'ReferenceNo'},
        Amount:{header:'Amount'},
        Memo:{header:'Memo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRecurringBankCashRcv?'+req._parsedUrl.query;
    dao.searchAppRecurringBankCashRcv(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRecurringBankCashRcvSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
