/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRptProfitAndLossSearch',
    Heading:'AppRptProfitAndLoss',
    RptProfitAndLossId:{label :'RptProfitAndLossId'},
    RptProfitAndLossName:{label :'RptProfitAndLossName'},
    DepartmentFrom:{label :'DepartmentFrom'},
    DepartmentTo:{label :'DepartmentTo'},
    CurrencyId:{label :'CurrencyId'},
    Revenue:{label :'Revenue'},
    RevenueExpenditure:{label :'RevenueExpenditure'},
    GrossMargin:{label :'GrossMargin'},
    OperationalExpenditure:{label :'OperationalExpenditure'},
    OperatingProfit:{label :'OperatingProfit'},
    OtherRevenue:{label :'OtherRevenue'},
    OtherExpenditure:{label :'OtherExpenditure'},
    NetProfit:{label :'NetProfit'},
    ComparativeRevenue:{label :'ComparativeRevenue'},
    ComparativeRevenueExpenditure:{label :'ComparativeRevenueExpenditure'},
    ComparativeGrossMargin:{label :'ComparativeGrossMargin'},
    ComparativeOperationalExpenditure:{label :'ComparativeOperationalExpenditure'},
    ComparativeOperatingProfit:{label :'ComparativeOperatingProfit'},
    ComparativeOtherRevenue:{label :'ComparativeOtherRevenue'},
    ComparativeOtherExpenditure:{label :'ComparativeOtherExpenditure'},
    ComparativeNetProfit:{label :'ComparativeNetProfit'},
    DateCreated:{label :'DateCreated'},
    CreatedBy:{label :'CreatedBy'},
    AppRptProfitAndLoss:{Heading:'AppRptProfitAndLoss',
        RptProfitAndLossId:{header:'RptProfitAndLossId'},
        RptProfitAndLossName:{header:'RptProfitAndLossName'},
        DepartmentFrom:{header:'DepartmentFrom'},
        DepartmentTo:{header:'DepartmentTo'},
        CurrencyId:{header:'CurrencyId'},
        Revenue:{header:'Revenue'},
        RevenueExpenditure:{header:'RevenueExpenditure'},
        GrossMargin:{header:'GrossMargin'},
        OperationalExpenditure:{header:'OperationalExpenditure'},
        OperatingProfit:{header:'OperatingProfit'},
        OtherRevenue:{header:'OtherRevenue'},
        OtherExpenditure:{header:'OtherExpenditure'},
        NetProfit:{header:'NetProfit'},
        ComparativeRevenue:{header:'ComparativeRevenue'},
        ComparativeRevenueExpenditure:{header:'ComparativeRevenueExpenditure'},
        ComparativeGrossMargin:{header:'ComparativeGrossMargin'},
        ComparativeOperationalExpenditure:{header:'ComparativeOperationalExpenditure'},
        ComparativeOperatingProfit:{header:'ComparativeOperatingProfit'},
        ComparativeOtherRevenue:{header:'ComparativeOtherRevenue'},
        ComparativeOtherExpenditure:{header:'ComparativeOtherExpenditure'},
        ComparativeNetProfit:{header:'ComparativeNetProfit'},
        DateCreated:{header:'DateCreated'},
        CreatedBy:{header:'CreatedBy'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRptProfitAndLoss?'+req._parsedUrl.query;
    dao.searchAppRptProfitAndLoss(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRptProfitAndLossSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
