/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppOpeningBalanceSearch',
    Heading:'AppOpeningBalance',
    OpeningBalanceId:{label :'OpeningBalanceId'},
    AccountNo:{label :'AccountNo'},
    BeginningBalance:{label :'BeginningBalance'},
    AppOpeningBalance:{Heading:'AppOpeningBalance',
        OpeningBalanceId:{header:'OpeningBalanceId'},
        AccountNo:{header:'AccountNo'},
        BeginningBalance:{header:'BeginningBalance'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppOpeningBalance?'+req._parsedUrl.query;
    dao.searchAppOpeningBalance(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppOpeningBalanceSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
