/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRefCitySearch',
    Heading:'AppRefCity',
    CityId:{label :'CityId'},
    Name:{label :'Name'},
    Details:{label :'Details'},
    ProvinceId:{label :'ProvinceId'},
    AppRefCity:{Heading:'AppRefCity',
        CityId:{header:'CityId'},
        Name:{header:'Name'},
        Details:{header:'Details'},
        ProvinceId:{header:'ProvinceId'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRefCity?'+req._parsedUrl.query;
    dao.searchAppRefCity(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRefCitySearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
