/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppRecurringBankWcFaSearch',
    Heading:'AppRecurringBankWcFa',
    RecurringBankWcFaId:{label :'RecurringBankWcFaId'},
    RecurringBankWriteCheckId:{label :'RecurringBankWriteCheckId'},
    AccountNo:{label :'AccountNo'},
    DepartmentId:{label :'DepartmentId'},
    Amount:{label :'Amount'},
    JobOrderNo:{label :'JobOrderNo'},
    AppRecurringBankWcFa:{Heading:'AppRecurringBankWcFa',
        RecurringBankWcFaId:{header:'RecurringBankWcFaId'},
        RecurringBankWriteCheckId:{header:'RecurringBankWriteCheckId'},
        AccountNo:{header:'AccountNo'},
        DepartmentId:{header:'DepartmentId'},
        Amount:{header:'Amount'},
        JobOrderNo:{header:'JobOrderNo'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppRecurringBankWcFa?'+req._parsedUrl.query;
    dao.searchAppRecurringBankWcFa(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppRecurringBankWcFaSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
