/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankReconciliationSearch',
    Heading:'AppBankReconciliation',
    BankReconciliationId:{label :'BankReconciliationId'},
    AccountNo:{label :'AccountNo'},
    CurrentAccountDate:{label :'CurrentAccountDate'},
    CurrentAccountBalance:{label :'CurrentAccountBalance'},
    AppBankReconciliation:{Heading:'AppBankReconciliation',
        BankReconciliationId:{header:'BankReconciliationId'},
        AccountNo:{header:'AccountNo'},
        CurrentAccountDate:{header:'CurrentAccountDate'},
        CurrentAccountBalance:{header:'CurrentAccountBalance'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppBankReconciliation?'+req._parsedUrl.query;
    dao.searchAppBankReconciliation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppBankReconciliationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
