/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppWorkStationSearch',
    Heading:'AppWorkStation',
    WorkStationId:{label :'WorkStationId'},
    WorkStationName:{label :'WorkStationName'},
    WorkStationDesc:{label :'WorkStationDesc'},
    AppWorkStation:{Heading:'AppWorkStation',
        WorkStationId:{header:'WorkStationId'},
        WorkStationName:{header:'WorkStationName'},
        WorkStationDesc:{header:'WorkStationDesc'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppWorkStation?'+req._parsedUrl.query;
    dao.searchAppWorkStation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppWorkStationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
