/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppCompanyInfoAccPeriodSearch',
    Heading:'AppCompanyInfoAccPeriod',
    AccountingPeriodId:{label :'AccountingPeriodId'},
    Month:{label :'Month'},
    Year:{label :'Year'},
    YearEnd:{label :'YearEnd'},
    IsCreateChartOfAccount:{label :'IsCreateChartOfAccount'},
    FileName:{label :'FileName'},
    AppCompanyInfoAccPeriod:{Heading:'AppCompanyInfoAccPeriod',
        AccountingPeriodId:{header:'AccountingPeriodId'},
        Month:{header:'Month'},
        Year:{header:'Year'},
        YearEnd:{header:'YearEnd'},
        IsCreateChartOfAccount:{header:'IsCreateChartOfAccount'},
        FileName:{header:'FileName'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchAppCompanyInfoAccPeriod?'+req._parsedUrl.query;
    dao.searchAppCompanyInfoAccPeriod(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('AppCompanyInfoAccPeriodSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
