/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductSellingPriceWrite',
    Heading:'AppProductSellingPrice',
    ProductPriceId:{label :'ProductPriceId'},
    ChangedDate:{label :'ChangedDate'},
    ChangedBy:{label :'ChangedBy'},
    NormalPriceEffectiveDate:{label :'NormalPriceEffectiveDate'},
    CalculationMethod:{label :'CalculationMethod'},
    AmountOfCalculationMethod:{label :'AmountOfCalculationMethod'},
    RoundUp:{label :'RoundUp'},
    SmallestUnit:{label :'SmallestUnit'},
    PricingBase:{label :'PricingBase'},
    IsIncludeTaxToSellingPrice:{label :'IsIncludeTaxToSellingPrice'},
    IsSelectedItem:{label :'IsSelectedItem'},
    CurrentSellingPrice:{label :'CurrentSellingPrice'},
    NewSellingPrice:{label :'NewSellingPrice'},
    EffectiveDateOfNewSellingPrice:{label :'EffectiveDateOfNewSellingPrice'},
    ProductId:{label :'ProductId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readAppProductSellingPrice(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('AppProductSellingPriceWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeAppProductSellingPrice(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppProductSellingPriceWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
