/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppBankReconciliationDetailWrite',
    Heading:'AppBankReconciliationDetail',
    BankReconciliationDetailId:{label :'BankReconciliationDetailId'},
    BankReconciliationId:{label :'BankReconciliationId'},
    Date:{label :'Date'},
    ReferenceNo:{label :'ReferenceNo'},
    Note:{label :'Note'},
    DebitAmount:{label :'DebitAmount'},
    CreditAmount:{label :'CreditAmount'},
    IsSelected:{label :'IsSelected'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readAppBankReconciliationDetail(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('AppBankReconciliationDetailWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeAppBankReconciliationDetail(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppBankReconciliationDetailWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
