/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductWrite',
    Heading:'AppProduct',
    ProductId:{label :'ProductId'},
    ProductCode:{label :'ProductCode'},
    ProductDesc:{label :'ProductDesc'},
    BaseUnit:{label :'BaseUnit'},
    ReportUnit:{label :'ReportUnit'},
    ProductGroup1st:{label :'ProductGroup1st'},
    ProductGroup2nd:{label :'ProductGroup2nd'},
    ProductGroup3rd:{label :'ProductGroup3rd'},
    ProductGroup4th:{label :'ProductGroup4th'},
    AliasCode:{label :'AliasCode'},
    IsUseSerialNumber:{label :'IsUseSerialNumber'},
    IsUseLot:{label :'IsUseLot'},
    IsConsignment:{label :'IsConsignment'},
    IsNotActive:{label :'IsNotActive'},
    IsSeasonalProduct:{label :'IsSeasonalProduct'},
    ProductCategoryId:{label :'ProductCategoryId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readAppProduct(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('AppProductWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeAppProduct(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppProductWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
