/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'AppProductAcctCodeWrite',
    Heading:'AppProductAcctCode',
    ProductAcctCodeAndCogsId:{label :'ProductAcctCodeAndCogsId'},
    IsInventory:{label :'IsInventory'},
    IsPurchased:{label :'IsPurchased'},
    IsSold:{label :'IsSold'},
    AcctCodeCogs:{label :'AcctCodeCogs'},
    AcctCodeSales:{label :'AcctCodeSales'},
    AcctCodeSalesReturn:{label :'AcctCodeSalesReturn'},
    AcctCodeInventory:{label :'AcctCodeInventory'},
    AcctCodeConsignment:{label :'AcctCodeConsignment'},
    ProductId:{label :'ProductId'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',
    }
    dao.readAppProductAcctCode(jsonObj,function(err,rows) {
        parameter.record = rows[0];
        res.render('AppProductAcctCodeWritePage',parameter);
        console.log(parameter);        
    });
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,        
    }
    dao.writeAppProductAcctCode(jsonObj,function(err,rows) {    
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('AppProductAcctCodeWritePage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
